<?php

/* librarything: aperj/m1 dev key: 14e8ba9bf7f7860b13fb58ba60146228
 */

define('LIBRARYTHING_KEY', '14e8ba9bf7f7860b13fb58ba60146228');

function sfandfan_download_librarything_book_cover($isbn) {
    $isbn = '1427809321';
    $url = 'http://covers.librarything.com/devkey/'.LIBRARYTHING_KEY.'/medium/isbn/'.$isbn; //0545010225';
  // $cmd = 'http://www.librarything.com/services/rest/1.1/?apikey='.LIBRARYTHING_KEY.'&page_number='.$page_number.'&results=texts,authors&index1=subject_id&value1='.$subject_id;

    
    
}



?>
